version: '3'
services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    ports:
    - '5432:5432'
    environment:
    - POSTGRES_DB=yt_arch
    - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
    - ./.data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./.data/redis:/data
